### ISSUE TITLE
Can Leave Feedback for Myself

### ISSUE THREAD

**Issue by codethejason** [syscoin/syscoin2#128]
Currently, I can leave both merchant and buyer feedback on myself when I post an offer that I later purchase myself. This might lead to reputation abuse if the ratings are averaged because the point of feedback is to show other's peoples opinion about an alias. I think only other people should be able to leave feedback.

**Comment by sidhujag** [comment]
The thing is there is no way to determine if you own both aliases (buyer and merchant). I guess a quick check is to ensure that buyer/merchant feedback aliases are different but it won't stop the problem. As a sidenote the way that a reputation system might be more effective is through the use of the API like what BM is planning on doing, but getting the feedback and ensuring the aliases leaving the feedback themselves have some rating on them, to give more weight to those ratings. Therefor aliases without ratings will not give much weight to a rating while the ones that are used and are reputable will give higher weight on determining an aliases weighted feedback score.

**Comment by sidhujag** [comment]
Also if it is determined ever that someone is abusing the system they can be flagged and moderated through the sysban alias protocol. So their attempts at boosting their reputation will depend on if noone else found out about the abuse and got moderation to happen on them.

**Comment by codethejason** [comment]
Weighted ratings seem to be a good idea. Also, I guess there's no stopping from the abuser creating more aliases and opening trades with himself to give himself feedback.

**Comment by sidhujag** [comment]
Exactly, moderation will help and perhaps a "find weighted rating for this user" button which is an expensive deep search of that alias and all of its linked ratings to try to determine malpracticing behavior of that alias. The current rating system is cut and dry to avoid expensive checks that will clog up the consensus protocol since every node needs to run through every transaction (non-expired ones). It is better to build upon the API with more elaborate schemes unless we know for sure there is a way to solve the problem for which we don't. Weighted ratings may service some but may not help others, because currently most new users will have no ratings and might be truthful in their feedback. It might make sense to change the "core" rating system once there is a large enough user base to distinguish between cut and dry ratings versus weighted ratings and implement something that makes sense gathering statistical information regarding bad vs good feedback.

**Comment by codethejason** [comment]
Sounds good - I do agree the userbase at the moment is too small for weighted ratings to be accurate.
