### ISSUE TITLE
offer's cant have unlimited qty

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin2#31]
should be able to set the qty to -1 and have unlimited qty

**Comment by sidhujag** [comment]
fixed, test in latest build sebastien. Set offer to qty -1, try on resold offer too, it should set it to 1 automatically if its a certificate offer. Test with or without cert offers and resold offers to see that unlimited/cert offers are working properly

**Comment by sebastien1234** [comment]
Test 1: 

Unlimited qty with a certificate.

Result: does not work, and shouldn't since as soon as you put -1 and then select a cert, it greys-out the quantity and sets it to 1.

Test 2:

Create an offer with unlimited quantity

Result: Works, sets quantity to unlimited

In your last comment, @sidhujag you indicated "unlimited/cert offers are working properly", I'm not sure what you mean by cert offers since they cannot be unlimited as only one cert can be linked to an offer.


Test 3:

Resell offer with unlimited quantity

Result: Works


Test 4: 

Resell an offer with unlimited quantity and escrow

Result: Works


I think you can close #31

**Comment by sidhujag** [comment]
how come this one is not closed sebastien?
