### ISSUE TITLE
cannot find offer e04172883cb44f22 with Search

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin2#62]
cannot find offer e04172883cb44f22 with Search

**Comment by sidhujag** [comment]
did you set the offer to public by updating it after creation?

**Comment by ID453543435** [comment]
it not worck, imposible find offer e04172883cb44f22 with Search

**Comment by sidhujag** [comment]
Is your offer still set to private?

**Comment by dwasyluk** [comment]
I actually just looked this offer up directly via the buy tab. You're unable to locate it in search because it is currently set to private. If you change it to public, it will be searchable. For more info please see this FAQ:  http://syscoin.org/faqs/make-items-visible-public-search/

`
{
  "offer": "e04172883cb44f22",
  "cert": "d27c03720aea540d",
  "txid": "dc33b68e9d5614a44084844dc3157ed374d9bc804088359b0f639c5035609638",
  "expires_in": 523013,
  "expired_block": 527384,
  "expired": 0,
  "height": "1784",
  "address": "1K3i1MvPCf8qFFZ3WerwA4gX9xrdEMEEkV",
  "category": "love",
  "title": "I want to marry",
  "quantity": "1",
  "currency": "SYS",
  "sysprice": 1.00000000,
  "price": "1.00",
  "ismine": "false",
  "commission": "0",
  "offerlink": "false",
  "offerlink_guid": "",
  "exclusive_resell": "ON",
  "private": "Yes",
  "btconly": "No",
  "alias_peg": "SYS_RATES",
  "description": "I want to marry\nhttps://pp.vk.me/c1934/u15436543/36894392/x_20d4920d.jpg\ncontact:\nhttps://vk.com/id15436543\nneed 16-18 old lady\n-----\ntags:\nlove sex child",
  "alias": "love",
  "accepts": [
  ]
}
`
